apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledata-pvc
  namespace: moodle
  labels:
    app.kubernetes.io/instance: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
